
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use ieee.math_real.all;

package vivado is
    -- FIFO generated by Vivado, used for values to send out of the FPGA.
    -- 1024x16, full, empty, prog full flag
    -- Common clock builtin FIFO
    component fifo_data is
        port (
            rst: in std_logic;
            clk: in std_logic;
            din: in std_logic_vector(15 downto 0);
            wr_en: in std_logic;
            rd_en: in std_logic;
            dout: out std_logic_vector(15 downto 0);
            full: out std_logic;
            empty: out std_logic;
            prog_full: out std_logic
        );
    end component fifo_data;

    -- Clocking wizard generated by Vivado
    -- clk_in1: 100 MHz
    -- sclk_adc: SCLK for the SPI interaction with the ADC. 16.66667MHz
    -- sclk2_adc: 2x SCLK for detecting SCLK edges. 33.33333MHz
    -- locked: unused
    component clk_wizard is
        port (
            clk_in1: in std_logic;
            main: out std_logic;
            sclk_adc: out std_logic;
            sclk2_adc: out std_logic;
            locked: out std_logic
        );
    end component clk_wizard;

    -- BRAM block for holding a frame with 16 bit elements
    -- clka: Main clock
    -- addra: Address to write/read to/from
    -- rsta: Reset, active high
    -- wea: Write enable
    -- dina: Data in, written on high wea
    -- douta: Data out, read always
    -- rsta_busy: unused
    component frame_bram_16b is
        port (
            clka: in std_logic;
            addra: in std_logic_vector(11 downto 0);
            rsta: in std_logic;
            wea: in std_logic;
            dina: in std_logic_vector(15 downto 0);
            douta: out std_logic_vector(15 downto 0);
            rsta_busy: out std_logic
        );
    end component frame_bram_16b;

    -- BRAM block for holding a frame with 21 bit elements
    -- clka: Main clock
    -- addra: Address to write/read to/from
    -- rsta: Reset, active high
    -- wea: Write enable
    -- dina: Data in, written on high wea
    -- douta: Data out, read always
    -- rsta_busy: unused
    component frame_bram_21b is
        port (
            clka: in std_logic;
            addra: in std_logic_vector(11 downto 0);
            rsta: in std_logic;
            wea: in std_logic;
            dina: in std_logic_vector(20 downto 0);
            douta: out std_logic_vector(20 downto 0);
            rsta_busy: out std_logic
        );
    end component frame_bram_21b;

    -- FIFO generated by Vivado, used for maintaining a window of samples.
    -- 256, full, empty flag
    -- Common clock builtin FIFO
    component fifo_window_256 is
        port (
            rst: in std_logic;
            clk: in std_logic;
            din: in std_logic_vector(15 downto 0);
            wr_en: in std_logic;
            rd_en: in std_logic;
            dout: out std_logic_vector(15 downto 0);
            full: out std_logic;
            empty: out std_logic
        );
    end component fifo_window_256;

    -- FIFO generated by Vivado, used for maintaining a window of samples.
    -- 64, full, empty flag
    -- Common clock builtin FIFO
    component fifo_window_64 is
        port (
            rst: in std_logic;
            clk: in std_logic;
            din: in std_logic_vector(15 downto 0);
            wr_en: in std_logic;
            rd_en: in std_logic;
            dout: out std_logic_vector(15 downto 0);
            full: out std_logic;
            empty: out std_logic
        );
    end component fifo_window_64;
end package vivado;

package body vivado is
end package body vivado;
