#!/usr/bin/env bash

here=$(dirname $0)

workdir=_work
base=${BASE-openstlinux}

mkdir -p $workdir

docker build -t som_os-$base .
docker run --entrypoint "$here/entrypoint.sh" --privileged \
    -v ~/.gitconfig:/etc/gitconfig \
    --mount type=bind,src=$(pwd),target=/home/ubuntu/work \
    -it som_os-$base /bin/bash
